// Create web server
// 1. Create web server
// 2. Create a file called index.html
// 3. Create a file called comments.js
// 4. Create a file called styles.css
// 5. Create a file called index.js
// 6. Create a file called server.js
// 7. Create a file called comments.json
// 8. Create a file called comments.html
// 9. Create a file called comments.css
// 10. Create a file called comments.json
// 11. Create a file called comments.js
// 12. Create a file called comments.html
// 13. Create a file called comments.css
// 14. Create a file called comments.json
// 15. Create a file called comments.js
// 16. Create a file called comments.html
// 17. Create a file called comments.css
// 18. Create a file called comments.json
// 19. Create a file called comments.js
// 20. Create a file called comments.html
// 21. Create a file called comments.css
// 22. Create a file called comments.json
// 23. Create a file called comments.js
// 24. Create a file called comments.html
// 25. Create a file called comments.css
// 26. Create a file called comments.json
// 27. Create a file called comments.js
// 28. Create a file called comments.html
// 29. Create a file called comments.css
// 30. Create a file called comments.json
// 31. Create a file called comments.js
// 32. Create a file called comments.html
// 33. Create a file called comments.css
// 34. Create a file called comments.json
// 35. Create a file called comments.js
// 36. Create a file called comments.html
// 37. Create a file called comments.css
// 38. Create a file called comments.json
// 39. Create a file called comments.js
// 40. Create a file called comments.html
// 41. Create a file called comments.css
// 42. Create a file called comments.json
// 43. Create a file called comments.js
// 44. Create a file called comments.html
// 45. Create a file called comments.css
// 46. Create a file called comments.json
//